### PR TITLE
Patches adding TLS support

### PR DESCRIPTION
**Pull request by talex5**
This builds and tests everything with all the TLS patches in. I assume we now wait for these patches to be accepted upstream and update to the release archives as they happen?

Things needing to be merged/released:

- [x] https://github.com/mirage/mirage-console/pull/33
- [x] https://github.com/mirage/ocaml-vchan/pull/60
- [x] https://github.com/mirage/mirage-tcpip/pull/98
- [x] https://github.com/mirage/mirage/pull/346 (mirage and mirage-types)
- [x] https://github.com/mirleft/ocaml-tls/pull/225 (superseded by https://github.com/mirleft/ocaml-tls/pull/258)
- [x] https://github.com/mirage/mirage-net-xen/pull/17
- [ ] https://github.com/mirage/ocaml-conduit/pull/37
- [x] https://github.com/mirleft/ocaml-nocrypto/pull/44
- [x] https://github.com/ocamllabs/ocaml-ctypes/pull/231
- [x] https://github.com/ocamllabs/ocaml-ctypes/issues/253
- [x] mirage-entropy
- [x] https://github.com/mirleft/ocaml-x509/commit/67488b67778c660af2759cd6ccab5376f40333c2 (needed by latest tls)
- [ ] https://github.com/mirleft/ocaml-nocrypto/issues/55 

And, afterwards:

- [ ]  https://github.com/mirage/mirage-skeleton/pull/67

### CODE REVIEW

**Comment by hannesm** [comment]
should https://github.com/mirleft/ocaml-nocrypto/pull/44 also be in this list??

**Comment by talex5** [comment]
@hannesm you're right - I didn't realise that still wasn't merged. Is there a problem with it?

**Comment by hannesm** [comment]
@talex5 I think it's fine, but it's @pqwy territory (whom I keep busy with various PRs) ;)

**Comment by talex5** [comment]
OK, I think we have all the required libraries in now! I added a Travis check to try building mirage-skeleton with `--xen` and also an `https_website` example that checks the TLS stuff builds for Xen.

**Comment by avsm** [comment]
mirage-console 2.1.1 in ocaml/opam-repository#3445

**Comment by pqwy** [comment]
https://github.com/mirleft/ocaml-nocrypto/pull/44 can be crossed off the list too.

**Comment by talex5** [comment]
@pqwy - not yet - it hasn't been released yet.

**Comment by avsm** [comment]
tcpip.2.2.3 is now released, so checked that one off.

**Comment by avsm** [comment]
I've added a ctypes.0.4.0 working version in mirage/mirage-dev#55, as that's necessary for the Xen compilation.

**Comment by hannesm** [comment]
I believe mirage-entropy needs to be somewhere in here... and to get this released, https://github.com/mirage/mirage-platform/pull/120 needs to be merged and released first..

**Comment by avsm** [comment]
mirage-platform 2.2.2 packages going out in ocaml/opam-repository#3667, so mirage-entropy is releasable now.

**Comment by avsm** [comment]
mirage-entropy 0.2.0 is now released.

**Comment by hannesm** [comment]
there is no mirage-types-lwt-2.3.0?

**Comment by avsm** [comment]
am just adding it now!

**Comment by avsm** [comment]
ocaml/opam-repository#3694 has mirage-types-lwt.2.3.0

**Comment by amirmc** [comment]
Seems to me that mirleft/ocaml-nocrypto#44 was [released](https://github.com/mirleft/ocaml-nocrypto/releases/tag/0.3.1). Checking it off this list.

**Comment by talex5** [comment]
Seems various APIs had changed. I've updated the mirage and conduit PRs to the new APIs and removed the released components from this repository. Should be working again now.

**Comment by hannesm** [comment]
getting there... https://github.com/ocaml/opam-repository/pull/3770

**Comment by samoht** [comment]
I've checked more boxes, the missing bits are cleaning-up out TLS support for`conduit` and solving the entropy/nocrypto coupling (which is working on)

**Comment by pqwy** [comment]
That last bit is being tracked [here](https://github.com/mirleft/ocaml-nocrypto/issues/55).

**Comment by hannesm** [comment]
once mirage https://github.com/mirage/mirage/pull/394 PR is merged, and there are some releases (nocrypto, tls, mirage-entropy-xen), we'll need gmp-xen and zarith-xen; which might both be sensible to drag in via a `mirage-no-xen | (mirage-xen & x)` dependency (zarith onto gmp, nocrypto onto zarith)..

**Comment by samoht** [comment]
Indeed, we need the `mirage-no-xen` stuff. Do you want to look into that tomorrow (I'm fine to do it too).

**Comment by hannesm** [comment]
@samoht as a start https://github.com/mirage/mirage-dev/pull/63

**Comment by hannesm** [comment]
would also be nice to release a `mirage-xen` which is compatible with `cstruct-1.6.0` (e.g. master)

**Comment by samoht** [comment]
Almost done now, I've merged most of the things in `mirage-dev`. Only missing parts are optional but which would be nice to have:

- [ ] support cstruct 1.6.0 in mirage-xen
- [ ] better entropy and conduit integration (without mirage) https://github.com/mirage/ocaml-conduit/issues/67

**Comment by hannesm** [comment]
@samoht great work, thanks! I believe https://github.com/mirage/mirage-dev/pull/74 should be there as well. we can do some more testing, and then move it towards the main opam repository!?

**Comment by samoht** [comment]
Ha yes good point! Indeed, I plan to run a bit of more tests and then we can do a big pull-request to opam-repository with a coordinated announcement and blog post.

**Comment by hannesm** [comment]
this can be closed as well, or?

**Comment by talex5** [comment]
The extra tests added to `.travis-ci.sh` are probably worth keeping (it now checks we can build mirage-skeleton for Xen, and also tests building a tls example). Apart from that, if the work is now happening on master then we can close this.

**Comment by samoht** [comment]
@talex5 can you create a new PR with your travis improvement? thanks!

**Comment by talex5** [comment]
@samoht I've made a PR here: https://github.com/mirage/mirage-dev/pull/77

The mirage-skeleton TLS example was for the old API, so I've left that out for now. I assume someone else has a test for the new API.

**Comment by samoht** [comment]
Thanks all for the effort, we are almost seeing the light :-)

**Comment by avsm** [comment]
Just one thing I'm missing for the record: https://github.com/mirleft/ocaml-tls/pull/250#issuecomment-98160187 -- will release this to get it working with cstruct 1.6.0 (@samoht tells me its cstruct 1.5.0 only atm)

**Comment by hannesm** [comment]
this PR in tls is intentionally not merged, to not introduce a dependency on `cstruct-1.6.0`. there are various other libraries (such as mirage-xen and dns) which required `< cstruct-1.6.0`.. will merge the tls PR (and maybe re-release) once releases of mirage-xen/dns/.. are done which support `cstruct >= 1.6.0`.

**Comment by hannesm** [comment]
also, keep in mind that tls-0.5.0 already works flawlessly with cstruct-1.6.0!

**Comment by pqwy** [comment]
Congrats, everyone!

This turned out to be soooo much hairier than initially expected... :smile:

**Pull request closed without merging**
