### PR TITLE
automatically add {>= 3.0.0} version constraints for mirage-types{-lwt}

### PR DESCRIPTION
**Pull request by yomimono**
All affected files have had a run through an automated parser/printer and no attempt has been made to preserve whitespace.

### CODE REVIEW

**Comment by samoht** [comment]
I think @gashe had some scripts to preserve the whitespaces. Let me try to find it....

**Comment by samoht** [comment]
Hum I cannot find it anymore (I just found https://github.com/gasche/opam/blob/ocamlbuild-migration-script/admin-scripts/add_ocamlbuild_dependency.ml which does not keep the whitespaces).

However, @AltGr might have some secret scripts running around as he managed to keep the whitespaces in https://github.com/ocaml/opam-repository/pull/5224

**Comment by gasche** [comment]
I did not preserve the whitespace on my ocamlbuild change (in particular some comments in the "depends" information were lost and I had to restore them manually), but @AltGr changed the printer at that time to detect unchanged fields and print them exactly unchanged -- which means that whitespace is only lost there, and that diffs are much easier to review.

I guess the question is: what script did you use to generate the change, and with which version of `opam-libs`?

**Comment by gasche** [comment]
I trunk `opamFile.mli`:

```ocaml
  (** Writes an opam file, but preserving the existing formatting as much as
      possible. The format is taken from the file that is being overwritten
      unless [format_from] is specified. *)
  val write_with_preserved_format:
    ?format_from:(t typed_file) -> t typed_file -> t -> unit
```

**Comment by yomimono** [comment]
This patch set was generated with a script that uses `opam-file-format`.

**Comment by samoht** [comment]
(I'm testing the new GH feature to resolve conflicts...)

**Comment by AltGr** [comment]
The format-preserving reprinter is implemented at a higher level, so `opam-file-format` is not enough, you would need to link `opam-core` and `opam-format` and use the `OpamFile.OPAM` module. Which, for a repository-rewriting script, should be easier anyway.

Or you would need to reimplement format preserving, which uses the precise positions returned by the parser to extract the corresponding substrings.

**Comment by avsm** [comment]
Why bother with whitespace? Let's just normalize the whole repo and move on with the actual constraints -- unless it makes conflict resolution easier somehow?

**Comment by samoht** [comment]
Because these are file read by human (and maintainers) too so formatting is important. And it will make resync with upstream even more painful that I already plan it will be.

**Comment by samoht** [comment]
With the help of @AltGr I have a whitespace-preserving constrainer up and running. I'll make a new big PR pretty soon.

**Comment by samoht** [comment]
Closing as #251 has been merged.

**Pull request closed without merging**
