### PR TITLE
Add mirage 2.5.0 (tls support) and new conduit

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
Hum, I've now got:

```
 sg:true gso_tcpv4:true rx_copy:true rx_flip:false smart_poll:false
ARP: sending gratuitous from 192.168.33.42
Manager: configuration done
ARP: transmitting probe -> 192.168.33.1
ARP: updating 192.168.33.1 -> 0a:00:27:00:00:00
[192.168.33.1:54955] TLS ok
Cannot handle page request order 8!
Fatal error: out of memory.
Mirage exiting with status 2
Do_exit called!
base is 0x42fa30 caller is 0x21375f
base is 0xf8000 caller is 0x47c74858788d4800
base is 0x10843c7483b Page fault at linear address 10843c74843, rip 23bd37, regs 000000000042f948, sp 42f9f0, our_sp 000000000042f908, code 0
RIP: e030:[<000000000023bd37>]
RSP: e02b:000000000042f9f0  EFLAGS: 00010006
RAX: 0000000000000016 RBX: 0000010843c7483b RCX: 00000000000007c5
RDX: 00000000000007c5 RSI: 000000000042f840 RDI: 0000000000000004
RBP: 000000000042fa30 R08: 00000000000007c4 R09: 0000000000000020
R10: 0000000000000016 R11: 0000000000000000 R12: 0000000000000000
R13: 0000000000000000 R14: 000000000ae01008 R15: 0000000000800fe8
base is 0x42fa30 caller is 0x21375f
base is 0xf8000 caller is 0x47c74858788d4800
base is 0x10843c7483b Page fault in pagetable walk (access to invalid memory?).
```

while using mirage-seal. To reproduce, follow the steps in https://github.com/samoht/mirage-dev and try to open a TLS connection to the unikernel. Any idea?

**Comment by hannesm** [comment]
how much memory does the vm get?

**Comment by samoht** [comment]
An other backtrace:
```
[192.168.33.1:55247] TLS ok
[192.168.33.1:55248] TLS ok
Cannot handle page request order 8!
Fatal error: out of memory.
Mirage exiting with status 2
Do_exit called!
base is 0x41fa10 caller is 0x2098df
base is 0xf8000 caller is 0xe8c308c483481889
base is 0x4800000400f840c7 GPF rip: 231eb7, error_code=0
RIP: e030:[<0000000000231eb7>]
RSP: e02b:000000000041f9d0  EFLAGS: 00010002
RAX: 000000000000001b RBX: 4800000400f840c7 RCX: 00000000000007e7
RDX: 00000000000007e7 RSI: 000000000041f820 RDI: 0000000000000004
RBP: 000000000041fa10 R08: 00000000000007e6 R09: 0000000000000020
R10: 000000000000001b R11: 0000000000000000 R12: 0000000000000000
R13: 0000000000000000 R14: 000000000ae01008 R15: 0000000000800ff0
base is 0x41fa10 caller is 0x2098df
base is 0xf8000 caller is 0xe8c308c483481889
base is 0x4800000400f840c7 GPF rip: 2322a7, error_code=0
RIP: e030:[<00000000002322a7>]
RSP: e02b:000000000041f8f8  EFLAGS: 00010016
RAX: 000000000000001b RBX: 4800000400f840c7 RCX: 0000000000000a12
RDX: 0000000000000a12 RSI: 000000000041f748 RDI: 0000000000000004
RBP: 000000000041f928 R08: 0000000000000211 R09: 0000000000000020
R10: 000000000000001b R11: 0000000000000000 R12: 0000000000000000
R13: 0000000000000000 R14: 000000000ae01008 R15: 0000000000800ff0
base is 0x41f928 caller is 0xae01008
base is 0x800ff0 caller is 0x0

41f8e0: f8 f8 41 00 00 00 00 00 2b e0 00 00 00 00 00 00
41f8f0: a7 22 23 00 00 00 00 00 03 00 00 00 30 00 00 00
41f900: d0 f9 41 00 00 00 00 00 c7 40 f8 00 04 00 00 48
41f910: 10 fa 41 00 00 00 00 00 00 00 00 00 00 00 00 00

41f910: 10 fa 41 00 00 00 00 00 00 00 00 00 00 00 00 00
41f920: 2f 25 23 00 00 00 00 00 f0 0f 80 00 00 00 00 00
41f930: 08 10 e0 0a 00 00 00 00 00 00 00 00 00 00 00 00
41f940: 00 00 00 00 00 00 00 00 10 fa 41 00 00 00 00 00

232290: 48 8b 5d 20 0f 1f 40 00 48 89 de 31 c0 bf df 28
2322a0: 25 00 e8 d9 cf ff ff 48 8b 73 08 31 c0 bf ed 28
2322b0: 25 00 e8 c9 cf ff ff 48 8b 1b 48 85 db 75 d9 4c
2322c0: 8b a5 98 00 00 00 49 81 fc ff 0f 00 00 76 61 49
```

Adding the memory doesn't seem to change anything.

**Comment by samoht** [comment]
With a bigger memory `1024`  I got:

```
[192.168.33.1:55469] TLS ok
Cannot handle page request order 15!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle page request order 0!
Cannot handle
```

**Comment by samoht** [comment]
So it seem to be related by using both HTTP and TLS. HTTP only works fine, TLS only works fine. The two together and everything explodes. I have no idea where this could come from (I've tried to trace it a little bit in `mirage-tcpip/channel` or `mirage-http` but with no luck).

**Comment by samoht** [comment]
I managed to get `mirage-seal` work with a version of a repository before the renaming of `gmp` to `gmp-xen`. Even in that case, it seems that there is still a `out of memory` exception raised at some point though ...

**Comment by samoht** [comment]
Is someone able to reproduce the issue or it is only me?@talex5 or @djs55 any thought on this? how I am supposed to debug this? :-)

**Comment by avsm** [comment]
First thing is to bisect the problem.  Can you reproduce it in Unix with tuntap?

**Comment by samoht** [comment]
I'm using an old vagrant image where tuntap doesn't seem to work so I cannot test easily. I'll try to find a working env where it is easier to bisect.

**Comment by talex5** [comment]
Works for me (Xen running under VirtualBox on x86_64):

```
 sg:true gso_tcpv4:true rx_copy:true rx_flip:false smart_poll:false
ARP: sending gratuitous from 10.0.0.13
Manager: configuration done
ARP responding to: who-has 10.0.0.13?
ARP: transmitting probe -> 10.0.0.1
ARP: updating 10.0.0.1 -> fe:ff:ff:ff:ff:ff
[10.0.0.1:50595] TLS ok
[1] serving //10.0.0.13/.
[1] closing.
ARP: timeout 10.0.0.1
```

**Comment by samoht** [comment]
which packages do you have?

```
$ opam list
vagrant@virtualbox-xen:~$ opam list
# Installed packages for gmp-xen:
asn1-combinators        0.1.2  Combinators for expressing ASN.1 grammars in OCaml
base-bigarray            base  Bigarray library distributed with the OCaml compiler
base-bytes             legacy  Bytes compatibility library distributed with ocamlfind
base-no-ppx              base  A pseudo-library to indicate lack of extension points support
base-threads             base  Threads library distributed with the OCaml compiler
base-unix                base  Unix library distributed with the OCaml compiler
base64                  2.0.0  Base64 encoding and decoding library
camlp4                 4.01.0  Camlp4 is a system for writing extensible parsers for programming languages
cmdliner                0.9.7  Declarative definition of command line interfaces for OCaml
cohttp                 0.17.1  HTTP library for Lwt, Async and Mirage
conduit                 0.8.3  Network connection library for TCP and SSL
conf-gmp                    1  Virtual package relying on a GMP lib system installation.
conf-pkg-config           1.0  Virtual package relying on pkg-config installation.
cppo                    1.1.2  Equivalent of the C preprocessor for OCaml programs
crunch                  1.4.0  Convert a filesystem into a static OCaml module
cstruct                 1.4.0  access C structures via a camlp4 extension
ctypes                  0.4.1  Combinators for binding to C libraries without writing any C.
depext                    0.5  Query and install external dependencies of OPAM packages
dns                    0.14.1  DNS client and server implementation
dolog                     1.0  the dumb OCaml logger (lazy and optionally colorful)
fieldslib           109.20.03  Syntax extension to define first class values representing record fields, to get and set record fields, iterate and fold over all fields of a record and creat
gmp-xen                 6.0.0  The GNU Multiple Precision Arithmetic Library
io-page                 1.5.1  Allocate memory pages suitable for aligned I/O
ipaddr                  2.6.1  IP (and MAC) address representation library
lwt                     2.4.8  A cooperative threads library for OCaml
magic-mime              1.0.0  Convert file extensions to MIME types
mirage                  2.5.0  The Mirage library operating system
mirage-clock-unix       1.0.0  A Mirage-compatible Clock library for Unix
mirage-clock-xen        1.0.0  A Mirage-compatible Clock library for Xen
mirage-conduit          2.2.0  Virtual package for the Mirage Conduit transports
mirage-console          2.1.3  A Mirage-compatible Console library for Xen and Unix
mirage-dns              2.0.0  Virtual package for the Mirage DNS transports
mirage-entropy-xen      0.3.0  Mirage entropy device
mirage-http             2.2.0  Mirage HTTP client and server driver
mirage-net-unix         2.2.0  Ethernet network driver for Mirage, using tuntap
mirage-net-xen          1.4.1  Ethernet network device driver for Mirage/Xen
mirage-profile            0.4  Collect profiling information
mirage-seal          ~unknown (pinned)
mirage-types            2.3.0  Module type definitions for Mirage-compatible applications
mirage-types-lwt        2.3.0  Lwt module type definitions for Mirage-compatible applications
mirage-unix             2.3.1  Mirage OS library for Unix compilation
mirage-xen              2.3.1  MirageOS library for Xen
mirage-xen-minios       0.7.0  Xen MiniOS guest operating system library
mirage-xen-ocaml        2.3.1  MirageOS headers for the OCaml runtime
mirage-xen-posix        2.3.1  MirageOS library for posix headers
nocrypto                0.4.0  Small functional-style crypto library.
ocaml-src              4.01.0  Compiler sources
ocamlfind               1.5.5  A library manager for OCaml
ocplib-endian             0.8  Optimised functions to read and write int16/32/64 from strings and bigarrays, based on new primitives added in version 4.01.
ounit                   2.0.0  Unit testing framework loosely based on HUnit. It is similar to JUnit, and other XUnit testing frameworks
re                      1.3.2  RE is a regular expression library for OCaml
sexplib             111.17.00  Library for serializing OCaml values to and from S-expressions
shared-memory-ring      1.1.1  Shared memory rings for RPC and bytestream communications.
stringext               1.3.1  Extra string functions for OCaml
tcpip                   2.4.2  Userlevel TCP/IP stack
tls                     0.5.0  Transport Layer Security (TLS) in OCaml
tuntap                  1.0.0  TUN/TAP bindings
type_conv           111.13.00  Library for building type-driven syntax extensions
uri                     1.8.0  RFC3986 URI/URL parsing library
vchan                   2.0.2  Xen Vchan implementation
x509                    0.3.1  X.509 certificate (RFC5280) library
xen-evtchn              1.0.6  Xen event channel bindings.
xen-gnt                 2.2.0  Xen grant table bindings
xenstore                1.2.5  Xenstore protocol clients and server
xenstore_transport      0.9.4  Low-level libraries for connecting to a xenstore service on a xen host.
zarith                    1.3  Implements arithmetic and logical operations over arbitrary-precision integers
```

(note I have `gmp-xen` instead of `gmp` but that gives me more or less the same result)

**Comment by talex5** [comment]
Actually, I'm seeing memory errors now when serving larger files.

**Comment by samoht** [comment]
@hannesm managed to reproduce with tuntap

**Comment by samoht** [comment]
and actually it seems to happen with sockets as well.

**Comment by talex5** [comment]
Seems to be lots of allocing coming from `camlStream__entry`. Any idea what that is?

**Comment by samoht** [comment]
Reverting to `tcpip.2.4.1` makes the socket version works again...

**Comment by samoht** [comment]
ok I have a fix, there is an infinite loop in the channel code for `read_until`. Fixing that with a test soon.

**Comment by samoht** [comment]
The fix is https://github.com/mirage/mirage-tcpip/pull/131. Thanks all for your help!

**Comment by talex5** [comment]
Ah, well spotted!

I wonder if we should track these problems in case they indicate a bad API. In the channel API's `read_until` it seems that there are three outcomes:

- The character is found and the string up to there is returned (`true, result`)
- The character is not found yet, but there will be more input later, so check again (`false, nonempty_buf`)
- The character will never be found, so give up (`false, empty_buf`)

Perhaps we should represent this with three variants? (e.g. `Found of buffer | Cont of buffer | End_of_file`) Although that does introduce an "impossible" result of (`Cont empty_buffer`).

**Comment by samoht** [comment]
yes the channel API is full of inconsistency. We should definitely keep a list of them somewhere. I'll create a page on the mirage wiki.

**Pull request merged**
