### PR TITLE
Add mirage+functoria

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
weird error here:

```
mirage =>
  cd /home/travis/build/mirage/mirage-dev/mirage-skeleton/conduit_server_manual && ocamlbuild -use-ocamlfind -tags annot,bin_annot -pkg mirage config.cmxs
mirage: unknown option `-t'.
Usage: mirage configure [OPTION]... 
Try `mirage configure --help' or `mirage --help' for more information.
make: *** [conduit_server_manual-configure] Error 1
```

All the previous configuration worked fine, so not sure what is it about. @Drup do you have any idea where it could come from? I'll investigate later.

**Comment by Drup** [comment]
Wow, no, I don't know.

**Comment by Drup** [comment]
Ok, I think I know. the config.ml doesn't compile and there is a weirdness in the error handling in this case.

**Comment by samoht** [comment]
That's a hard-to-decipher compilation error message :-)

**Comment by Drup** [comment]
Yeah, I will have to investigate but the underlying issue is fixed.

**Pull request merged**
