### PR TITLE
automatically add {>= 3.0.0} version constraints for mirage-types{-lwt}

### PR DESCRIPTION
**Pull request by samoht**
superseed #246

It's not perfect but it is less intrusive.

### CODE REVIEW

**Comment by samoht** [comment]
This is generated using https://github.com/yomimono/upperbound-constrainer/pull/1 (thanks to invaluable help from @AltrGr)

The result is not yet perfect :p

**Comment by gasche** [comment]
It seems that the `test` condition is dropped? Unless that is intentional I would expect `{test}` to turn into `{test & >= "3.0.0"}`.

**Comment by samoht** [comment]
Thanks! I have re-added the `test` constraints.

**Comment by hannesm** [comment]
and somehow we should propagate those changes back to the originating repositories, shouldn't we?

**Comment by yomimono** [comment]
I want to automate that somehow, it's getting difficult to manage by hand.

**Pull request merged**
