### PR TITLE
sync mainly topkg>=0.8.0 constraints, but other things as well

### PR DESCRIPTION
**Pull request by hannesm**
- [x] https://github.com/mirage/mirage/pull/769
- [x] https://github.com/mirage/mirage-console/pull/57
- [x] https://github.com/mirage/mirage-clock/pull/25
- [x] https://github.com/mirage/mirage-protocols/pull/2
- [x] https://github.com/mirage/mirage-protocols/pull/3
- [x] https://github.com/mirage/mirage-stack/pull/1
- [x] https://github.com/mirage/mirage-random/pull/2
- [x] https://github.com/mirage/mirage-time/pull/1
- [x] https://github.com/mirage/mirage-net/pull/3
- [x] https://github.com/mirage/mirage-channel/pull/20
- [x] https://github.com/mirage/ocaml-dns/pull/124

### CODE REVIEW

**Comment by hannesm** [comment]
(CI fails on mirage-stack-lwt since it's using master, which requires (unused) mirage-protocols-lwt in both META and _tags)

**Comment by hannesm** [comment]
this and mentioned PRs are ready to be merged imho (but certainly an eye from @yomimono or @samoht (or whomever else) would be appreciated)

**Comment by hannesm** [comment]
(and some repos don't have travis activated, maybe someone can setup the hooks for mirage-random, mirage-time, mirage-stack, mirage-protocols)

**Comment by yomimono** [comment]
I enabled for mirage-stack and mirage-protocols just now having noticed that too, noted that mirage-time has no .travis.yml, will look at mirage-random

**Pull request merged**
