### PR TITLE
Delete released version of solo5.0.7.0

### PR DESCRIPTION
**Pull request by dinosaure**

### CODE REVIEW

**Comment by dinosaure** [comment]
It seems that we broke something about the `hvt` support but I don't know why. I will check tomorrow.

**Comment by dinosaure** [comment]
Ok the error seems about `base` - I will try to figure out why it does not compile anymore tomorrow.

**Comment by TheLortex** [comment]
If you rebase on top of `master` it shoud fix the issue (to get this commit: https://github.com/mirage/mirage-dev/commit/38f1101abd4c7bcd50f0fa0433495e38e383d093) . The CI doesn't yet try to merge the PR prior to testing (see https://github.com/ocurrent/mirage-ci/pull/11 that should be merged at some point)

**Comment by hannesm** [comment]
I force-pushed. Would be good to rename the base/parsexp/zarith to something easily recognizable, maybe a `~mirage` suffix?

**Comment by dinosaure** [comment]
Let's merge this PR and figure out then the layout we want for these packages.

**Pull request merged**
