### PR TITLE
ocaml-freestanding is now released to opam-repository

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Review by dinosaure — APPROVED** [review]

**Comment by hannesm** [comment]
maybe https://github.com/mirage/mirage/pull/1263 first needs to be merged to get the CI passing...

**Comment by hannesm** [comment]
I've no clue how to update mirage-ci " (run (network host) (shell "opam repo add opam https://github.com/ocaml/opam-repository.git#61c80509aec809b94b4ff7a505235f1ba605c756"))" and where the commit ID originates from...

**Comment by TheLortex** [comment]
In mirage-ci, the opam repository is updated once a day: (https://ci.mirage.io/job/2022-01-07/101236-git-clone-32c92b)
I've just triggered it so it should be good

**Comment by hannesm** [comment]
@TheLortex thanks

**Comment by hannesm** [comment]
CI is green now, this could be merged now :)

**Pull request merged**
