### PR TITLE
add datakit trunk libraries

### PR DESCRIPTION
**Pull request by avsm**
/cc @samoht @talex5

### CODE REVIEW

**Comment by samoht** [comment]
I'd like to make a proper release in the very short term, but I guess this will do for now.

**Comment by hannesm** [comment]
I'm slightly surprised, I thought this repository should contain all libraries leading to a mirage-3.0 release, and I hadn't yet realised that certain libraries (such as arp, datakit) would be part of it?  care to explain the release schedule / strategy (or is this secret?)

**Comment by samoht** [comment]
@hannesm I think the idea was to include it so we can have the docs online in one place :-)

Appart from that, we can use datakit to build easy runtime introspection libraries. Nothing really blocking the mirage 3.0 release at all, it is just a parallel track (and nothing secret!).

**Comment by samoht** [comment]
(see https://github.com/docker/vpnkit/pull/123 for an example of runtime introspection)

**Comment by hannesm** [comment]
ic. looks neat.  I fail to understand how the subsystems (datakit, 9p, vpnkit) interact (esp. what datakit does in there) -- is there some sort of more high-level overview anywhere?  certainly, exposing runtime information of a MirageOS unikernel via 9p would be great to have -- are there simpler examples than the one you mentioned?

**Comment by samoht** [comment]
short answer: no, no high-level description yet, but I am working on it. A simple example is maybe https://github.com/docker/datakit/blob/master/src/ivfs/ivfs_debug.ml where we expose all the logs sources (from `Logs.Src`) over 9p inside a `/debug` directory, so you can read the description in `/debug/src/<name>/descr` of each one and change their level but writing in `/debug/src/<name>/level`

**Comment by avsm** [comment]
> I'm slightly surprised, I thought this repository should contain all libraries leading to a mirage-3.0 release, and I hadn't yet realised that certain libraries (such as arp, datakit) would be part of it? care to explain the release schedule / strategy (or is this secret?)

Yes as @samoht said it's to have the docs be buildable.  What we'll do is also use this repo to update upper bounds in opam-repository, and then we can start cutting releases incrementally without breaking existing users.

**Pull request merged**
