### PR TITLE
mirage and functoria are now released

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
mirage-ci tries to install old versions of mirage. Need to add `opam install "mirage>=4.0"` somewhere :-)

**Comment by dinosaure** [comment]
I think you need a day to let `mirage-ci` to be synchronized with `opam-monorepo`

**Comment by TheLortex** [comment]
I've updated the opam-repository commit when this PR was created. But because it's a beta release it is not automatically selected by opam when querying mirage. Indeed the CI should be updated to query  mirage>=4

**Comment by dinosaure** [comment]
> Indeed the CI should be updated to query mirage>=4

Do we have a place where `mirage-ci` is developped?

**Comment by samoht** [comment]
A tentative fix for the CI is here: https://github.com/ocurrent/mirage-ci/pull/18

**Comment by TheLortex** [comment]
> > Indeed the CI should be updated to query mirage>=4
> 
> Do we have a place where `mirage-ci` is developed?

It's here: https://github.com/ocurrent/mirage-ci

**Comment by TheLortex** [comment]
I've merged the fix. Now the issue is that `4.0.0 > 4.0.0~beta1` so `mirage-runtime` is not selected.
```
 - mirage-runtime -> (problem)
     app-info-unix-monorepo zdev requires >= 4.0.0 & < 4.1.0
```

**Comment by dinosaure** [comment]
We probably need to lint every packages which requires "4.0.0" to `>= "4.0"` as @hannesm explained on the `opam-repository` PR.

**Comment by dinosaure** [comment]
The problem is here: https://github.com/mirage/mirage/blob/main/lib/mirage/mirage.ml#L324

Should we redo a release to update constraints? (/cc @samoht)

**Comment by dinosaure** [comment]
I pushed a new commit to see if we really fix our problem via an update of the minimal version required of `mirage{,-runtime}`.

**Pull request closed without merging**
