### PR TITLE
version of {mirage-}conduit that expects resultified tls.mirage

### PR DESCRIPTION
**Pull request by yomimono**

### CODE REVIEW

**Comment by yomimono** [comment]
Now we get all the way to discovering that after our regular `mirage-skeleton` chores, there are a few extra chores for us to do: https://travis-ci.org/mirage/mirage-dev/jobs/177752783#L1983 , failing on this step:

```
opam install -y -j2 datakit-ci datakit-server datakit-github datakit-client git-mirage charrua-unix logs-syslog
```

**Comment by avsm** [comment]
to summarise:

ocaml-git:
```
# File "lib/mirage/git_mirage.ml", line 348, characters 27-34:
# Error: Unbound type constructor G.error
# Command exited with code 2.
```

hvsock.dev
```
# File "lwt/flow_lwt_hvsock.mli", line 26, characters 57-62:
# Error: Unbound type constructor error
# Command exited with code 2.
```

logs-syslog

```
# File "src/logs_syslog_mirage.ml", line 13, characters 21-134:
# Error: This expression has type unit Lwt.t
#        but an expression was expected of type
#          (unit, UDP.error) Result.result Lwt.t
#        Type unit is not compatible with type
#          (unit, UDP.error) Result.result = (unit, UDP.error) result 
# Command exited with code 2.
```

**Comment by yomimono** [comment]
Tests pass without the additional stuff (see https://travis-ci.org/yomimono/mirage-dev/builds/177759962 ).  I'm merging the removal of the extra tests; @samoht @haesbaert @hannesm @djs55 @talex5 feel free to add back in when they're working if you like.

**Comment by hannesm** [comment]
I fixed logs-syslog, so much better now https://github.com/hannesm/logs-syslog/commit/9f59cca9415871ee4b9d8c4a4a9d5adfbc04015a

**Pull request merged**
