### PR TITLE
Jitsu v0.2

### PR DESCRIPTION
**Pull request by MagnusS**
- Add jitsu v0.2.0
- Fix URLs in jitsu v0.1

### CODE REVIEW

**Comment by MagnusS** [comment]
Hm, looks like the errors are unrelated to jitsu? 4.02 is not supported, due to Xenctrl

**Comment by samoht** [comment]
Errr, everything is broken! Can someone fix the 4.02 issue?

**Comment by samoht** [comment]
The 4.02 error is a duplicate of https://github.com/mirage/mirage-platform/issues/142, the other stackv4 error is very weird. I'll investigate ...

**Comment by samoht** [comment]
I've restarted the build now that mirage-xen-ocaml 2.3.4 is released.

**Comment by MagnusS** [comment]
Failed again with stackv4 errors...

**Comment by samoht** [comment]
The logs show one minor issue: ocaml-vchan does not compile with lwt 2.5.0,  and one major issue: my fork of mirage to add Irmin support isn't up-to-date. I can either remove it, move it to another branch or rename it (to `mirage-irmin`). @yomimono what to do you prefer? Are you using `mirage-dev` to build you Irmin-arp demo?

**Comment by yomimono** [comment]
@samoht Change at will; I'm not using the mirage fork's Irmin support at all.

**Comment by yomimono** [comment]
Re: the stackv4 error:

```
File "main.ml", line 60, characters 32-36:
Error: This expression has type
         Stackv41_I.t = Ipv4.Make(Stackv41_E)(Stackv41_A).t
       but an expression was expected of type
         Stackv41_A.t = Arpv4.Make(Stackv41_E)(Clock)(OS.Time).t
```

I suspect that the mirage-tcpip and mirage that are installed don't agree on whether the separating-ARP patches were applied.

**Comment by MagnusS** [comment]
Closing this PR as jitsu is in opam-repository now.

**Pull request closed without merging**
