### PR TITLE
+mirage-entropy-unix.dev package

### PR DESCRIPTION
**Pull request by avsm**

### CODE REVIEW

**Comment by hannesm** [comment]
uhm?  why?  this package was phased out more than a year ago (see https://github.com/mirage/mirage-entropy/commit/6a299853b37ede0d39efc77e1be2c24299e9b80f), and nocrypto provides unix entropy code since 0.4.0 (May 2015).

**Comment by avsm** [comment]
hm, missing dependency in a package... tracking it down (it was attempted to install during a bulk build).

**Comment by hannesm** [comment]
likely https://github.com/mirage/mirage/blob/c8b1f40095dd4776f01fa63bc34fa6325fa44957/Dockerfile.doc#L10 (search github.com for mirage-entropy-unix)... whoever put it there, it should not be there

**Comment by avsm** [comment]
also added a constraint to older versions so it should be a constraint failure soon ocaml/opam-repository#7438

**Pull request closed without merging**
