### PR TITLE
[Tracking] Better errors

### PR DESCRIPTION
**Pull request by talex5**
The mirage tool currently generates setup code that ignores the actual errors returned by the `connect` functions and prints a generic error. This PR tracks changes to mirage-types and to the various libraries to allow mirage to produce useful error messages. For example:

    Before:
    
        Fatal error: exception Failure("block11")
    
    After:
    
        *** Setup failure ***
    
        Error connecting block device "disk.img":
          block-unix: connecting "/home/user/work/cubieboard/skeleton/block/disk.img":
          Unix.Unix_error(Unix.ENOENT, "open", "/home/user/work/cubieboard/skeleton/block/disk.img")

### CODE REVIEW

**Comment by samoht** [comment]
Great work! As we've discussed in Marrakesh, I think the only thing that I don't really like in these patch is the fact that users have to explicitly wrap their job with `with_logs`. I'd feel much happier if it was an optional argument with a default log reporter, that we can enable/disable on the command-line line. Other than that I'm very happy with the rest of the patches! :-)

**Comment by talex5** [comment]
The attribute thing is easy to change. We need to wait for some solution to be accepted into Functoria first though:

https://github.com/mirage/functoria/pull/55

**Comment by samoht** [comment]
I'm not super happy with `error_string` too, would be great if we had `pp_error` instead?

**Comment by hannesm** [comment]
closing in favour of the merged https://github.com/mirage/mirage/pull/602 (and #155 in here). would be great to get the error types updates massaged into mirage-types and implementation libraries!

**Pull request closed without merging**
